s3_id: <%= ENV['AWS_S3_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['AWS_S3_SECRET_ACCESS_KEY'] %>
s3_bucket: <%= ENV['STAGING_AWS_S3_BUCKET'] %>
s3_endpoint: us-east-1
cache_control:
  "index.html": "no-cache, no-store, must-revalidate"
  "*": "max-age=315360000, no-transform, public"
index_document: index.html
error_document: 404.html
concurrency_level: 3
site: ../../public
treat_zero_length_objects_as_redirects: true
redirects:
  vision/index.html: /
