s3_id: <%= ENV['STAGING_AWS_S3_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['STAGING_AWS_S3_SECRET_ACCESS_KEY'] %>
s3_bucket: <%= ENV['STAGING_AWS_S3_BUCKET'] %>
s3_endpoint: us-east-1
cache_control:
  "index.html": "no-cache, no-store, must-revalidate"
  "*": "max-age=315360000, no-transform, public"
cloudfront_distribution_id: <%= ENV['STAGING_AWS_CLOUDFRONT_DISTRIBUTION_ID'] %>
cloudfront_invalidate_root: true
index_document: index.html
error_document: 404.html
concurrency_level: 3
site: ../../public
treat_zero_length_objects_as_redirects: true
redirects:
  blog/ios-chat-app-jsqmessagesviewcontroller/index.html: /blog/create-ios-chat-app-part1/
  introducing-syncano-a-real-time-sync-solution-for-complex-data-structures/index.html: /blog/introducing-syncano-a-real-time-sync-solution-for-complex-data-structures/
  how-to-create-push-notifications-with-syncano-on-osx/index.html: /blog/how-to-create-push-notifications-with-syncano-on-osx/
  communication-distributed-team/index.html: /blog/communication-distributed-team/
  newest-features-in-syncano-3-1/index.html: /blog/newest-features-in-syncano-3-1/
  the-six-most-important-things-to-consider-when-building-a-backend-solution/index.html: /blog/the-six-most-important-things-to-consider-when-building-a-backend-solution/
  syncano-named-one-of-150-most-promising-startups-in-the-world/index.html: /blog/syncano-named-one-of-150-most-promising-startups-in-the-world/
  5-signs-you-should-invest-in-a-backend-as-a-service/index.html: /blog/5-signs-you-should-invest-in-a-backend-as-a-service/
  syncanos-drawing-app-demo-and-code/index.html: /blog/syncanos-drawing-app-demo-and-code/
  misconceptions-backend-as-a-service/index.html: /blog/misconceptions-backend-as-a-service/
  beautiful-real-time-technology-apps/index.html: /blog/beautiful-real-time-technology-apps/
  every-backend-developer-should-focus-on-these-3-things/index.html: /blog/every-backend-developer-should-focus-on-these-3-things/
  the-critical-role-that-real-time-sync-plays-in-collaboration/index.html: /blog/the-critical-role-that-real-time-sync-plays-in-collaboration/
  how-to-create-great-applications-4-rules-to-follow/index.html: /blog/how-to-create-great-applications-4-rules-to-follow/
  is-your-data-secure/index.html: /blog/is-your-data-secure/
  startup-lessons-5-things-ive-learned/index.html: /blog/startup-lessons-5-things-ive-learned/
  our-top-takeaways-from-twilios-roadshow/index.html: /blog/our-top-takeaways-from-twilios-roadshow/
  how-to-create-a-cross-platform-app-in-minutes-with-appgyver-and-syncano/index.html: /blog/how-to-create-a-cross-platform-app-in-minutes-with-appgyver-and-syncano/
  3-ways-build-more-apps-less-time/index.html: blog/3-ways-build-more-apps-less-time/
  insane-but-true-internet-of-things/index.html: /blog/insane-but-true-internet-of-things/
  second-screen-living-room-smartphone-real-time-apps/index.html: /blog/second-screen-living-room-smartphone-real-time-apps/
  5-second-screen-real-time-apps/index.html: /blog/5-second-screen-real-time-apps/
  real-time-sync-apps-july/index.html: /blog/real-time-sync-apps-july/
  how-to-create-a-great-user-experience/index.html: /blog/how-to-create-a-great-user-experience/
  world-without-real-time-sync/index.html: /blog/world-without-real-time-sync/
  what-is-backend-as-a-service-baas/index.html: /blog/what-is-backend-as-a-service-baas/
  why-we-love-real-time-sync/index.html: /blog/why-we-love-real-time-sync/
  how-api-will-change-internet-of-things/index.html: /blog/how-api-will-change-internet-of-things/
  why-your-content-should-display-everywhere-cross-device/index.html: /blog/why-your-content-should-display-everywhere-cross-device/
  get-instant-notifications-syncano-ios/index.html: /blog/get-instant-notifications-syncano-ios/
  real-time-sync-apps-month-august-edition/index.html: /blog/real-time-sync-apps-month-august-edition/
  david-dekadt-havoctv-second-screen/index.html: /blog/david-dekadt-havoctv-second-screen/
  data-modeling-basics/index.html: /blog/data-modeling-basics/
  using-syncano-ios-library-swift-demotutorial/index.html: /blog/using-syncano-ios-library-swift-demotutorial/
  reactjs-reasons-why-part-1/index.html: /blog/reactjs-reasons-why-part-1/
  5-great-developer-tools-radar/index.html: /blog/5-great-developer-tools-radar/
  getting-started-reactjs-tutorial/index.html: /blog/getting-started-reactjs-tutorial/
  reasons-use-docker/index.html: /blog/reasons-use-docker/
  monitor-app-performance-crittercism/index.html: /blog/monitor-app-performance-crittercism/
  getting-started-swift-playground/index.html: /blog/getting-started-swift-playground/
  data-modeling-parent-child-relationships/index.html: /blog/data-modeling-parent-child-relationships/
  getting-started-docker/index.html: /blog/getting-started-docker/
  docker-workflow-fig-sh/index.html: /blog/docker-workflow-fig-sh/
  web-summit-official-beta-startup/index.html: /blog/web-summit-official-beta-startup/
  simplified-improved-development-docker/index.html: /blog/simplified-improved-development-docker/
  friendly-code-review/index.html: /blog/friendly-code-review/
  thank-you-shirts/index.html: /blog/thank-you-shirts/
  flask-micro-framework-introduction/index.html: /blog/flask-micro-framework-introduction/
  intro-flask-pt-2-creating-writing-databases/index.html: /blog/intro-flask-pt-2-creating-writing-databases/
  flask-databases-sqlalchemy/index.html: /blog/flask-databases-sqlalchemy/
  advanced-concepts-flask/index.html: /blog/advanced-concepts-flask/
  getting-know-javascript-intro/index.html: /blog/getting-know-javascript-intro/
  configuring-running-django-celery-docker-containers-pt-1/index.html: /blog/configuring-running-django-celery-docker-containers-pt-1/
  5-mistakes-great-developers-never-make/index.html: /blog/5-mistakes-great-developers-never-make/
  introduction-python/index.html: /blog/introduction-python/
  ios-chat-app-jsqmessagesviewcontroller/index.html: /blog/ios-chat-app-jsqmessagesviewcontroller/
  intro-to-express-js/index.html: /blog/intro-to-express-js/
  intro-to-node-js/index.html: /blog/intro-to-node-js/
  data-structures-in-javascript/index.html: /blog/data-structures-in-javascript/
  introduction-natural-language-processing/index.html: /blog/introduction-natural-language-processing/
  intro-angular-js/index.html: /blog/intro-angular-js/
  introduction-to-image-processing/index.html: /blog/introduction-to-image-processing/
  intro-to-syncano/index.html: /blog/intro-to-syncano/
  Syncano-is-speaking-at-Music-City-of-Code/index.html: /blog/syncano-is-speaking-at-music-city-of-code/
  data-data-everywhere/index.html: /blog/data-data-everywhere/
  codebox-run-your-own-code/index.html: /blog/codebox-run-your-own-code/
  how-can-i-use-codeboxes/index.html: /blog/how-can-i-use-codeboxes/
  data-at-the-speed-of-life/index.html: /blog/data-at-the-speed-of-life/
  user-management-for-your-apps/index.html: /blog/user-management-for-your-apps/
  syncano-is-going-places-literally/index.html: /blog/syncano-is-going-places-literally/
