# Site settings
title:       Syncano
email:       keganquimby@gmail.com
author:      Syncano
description: "A simple, beautiful theme for syncano.com."
baseurl:     ""
url:         "http://www.syncano.com"
permalink:    /:title
paginate:     6
paginate_path: "blog/page:num/"
exclude:
  - divshot.json
  - config.codekit