import React from 'react';
import Helmet from 'react-helmet';

export default React.createClass({

  getSEOConfig() {
    return {
      title: "Terms of Service",
      description: "Syncano's terms of service.",
      mixpanelTitle: "Terms of Service"
    }
  },
      
  render() {
    let SEO = this.getSEOConfig();

    return (
      <div>
        <Helmet
          title={SEO.title}
          meta={[
            {"name": "description", "content": SEO.description},
            {"name": "mixpanelTitle", "content": SEO.mixpanelTitle}
          ]}
        />
        <h1>Terms of Service</h1>
        <p>In order to use the Syncano API (the “Syncano API” or “API”), access the information contained on the Syncano website (the “Website”) or make use of the services provided by Syncano (the “Service” or “Services”), you (hereinafter referred to as “You”) must first read this agreement (the “Agreement”) and accept it. You may not make use of the Syncano API, Website or Services if You do not accept this Agreement and the terms therein.
          You accept the terms of the Agreement by clicking accept, by agreeing to the terms of the Agreement in the user interface for any Syncano Service, or by using the Syncano API or Services. In the latter case, You understand and agree that we will treat Your use of the Services as acceptance of the terms from that point onwards. BY USING THE SERVICE AND THE WEBSITE, YOU CONSENT TO THE TERMS AND CONDITIONS OF THESE TERMS OF SERVICE. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE PLEASE DO NOT USE THE WEBSITE AND/OR SERVICES.
          By putting a check mark next to I AGREE and clicking on SUBMIT or using the API or Services, You represent that You have read and agree to the terms and conditions of this Agreement which also include and incorporate Syncano’s Acceptable Use Policy, General Terms and Conditions and Privacy Policy. These terms and conditions will remain in effect throughout Your use of the Services and continue after this Agreement expires, cancels or is terminated. These terms and conditions are legally binding should You choose to register for the Service. You may not use the API or Services and may not accept the terms if (a) You are not of legal age to form a binding contract with us, or (b) You are a person barred from receiving the Services under the laws of the United States or other countries including the country in which You are resident or from which You use the Services. You agree to incorporate these Syncano policies into Your own products and policies and ensure that Your customers adhere to Syncano’s Terms.
          If You are accepting on behalf of Your employer or another entity, You represent and warrant that: (i) You have full legal authority to bind your employer, or the applicable entity, to these terms of service; (ii) You have read and understand this Agreement; and (iii) You agree, on behalf of the party that You represent, to this Agreement. If You don’t have the legal authority to bind Your employer or the applicable entity, please DO NOT put a check mark next to I AGREE and DO NOT click on SUBMIT or use the Services.
          We reserve the right to change these Terms of Service from time to time without notice by posting them on Syncano’s Website. When we do, we will also revise the “last update” date of these Terms of Service. Your continued use of the Service after such posting will constitute acceptance by You of such amendments.</p>
  
        <h3>1. Grant of Rights to Use Services</h3>
        <p>1.1 Subject to Your acceptance of and compliance with this Agreement and with the payment requirements for the Services, Syncano hereby grants You a limited, non-exclusive, non-transferable, non-sublicensable, revocable right and license during the Term of this Agreement in and under our intellectual property rights, to access and use the Services, solely in accordance with the terms and conditions of this Agreement. Unless explicitly stated otherwise, any new features provided by Syncano that enhance the current Services shall also constitute “Services” and shall be subject to these terms and conditions. You may not, nor allow any third party to, copy, distribute, sell, disclose, lend, transfer, convey, modify, decompile, disassemble or reverse engineer the Services for any purpose whatsoever. You may not allow any unauthorized third party to access the Services for any purpose whatsoever. Syncano retains all rights not expressly granted under this Agreement.</p>
        <p>1.2 You may write a software application or website (an “Application”) that interfaces with the Services. You acknowledge that we may change, deprecate or republish APIs for any Service or feature of a Service from time to time, and that it is Your responsibility to ensure that requests You make to or via our Service are compatible with then-current APIs for the Service. Syncano will attempt to inform You of any changes with reasonable notice so You can adjust Your Application, but we are under no obligation to do so.</p>
        <p>1.3 You may not remove, obscure, or alter any notice of any Syncano trademark, service mark or other intellectual property or proprietary right appearing on the Syncano Website or contained within the Services.</p>
        <p>1.4 Provided that You comply with the terms of this Agreement and our policies and procedures including the Acceptable Use Policy, You may use the Services to execute Applications owned or lawfully obtained by You. You are solely responsible for Your Applications, including any data, text, images or content contained therein.</p>
        <p>1.5 You are personally responsible for all traffic originating from Your Applications using Your account credentials to the Services. As such, You should protect Your authentication keys and security credentials. Actions taken using Your credentials shall be deemed to be actions taken by You, with all consequences including service termination, civil and criminal penalties.</p>
        <p>1.6 We may make available to You, for Your installation, copying and/or use in connection with the Services, from time to time, a variety of software, data and other content and printed and electronic documentation (the “Syncano Properties”). Subject to Your acceptance of and compliance with this Agreement, ongoing compliance with its terms and conditions with respect to the subject Service, and payment if and as required for Your right to use the subject Service, Syncano hereby grants to You a limited, non-exclusive, non-transferable, non-sublicensable, revocable license during the Term of this Agreement in and under our intellectual property rights in the Syncano Properties, only to install, copy and use the Syncano Properties solely in connection with and as necessary for Your use of such Services, solely in accordance with the terms and conditions of this Agreement.
          (a) The Syncano Properties may include, without limitation:
          The Syncano Website;
          Syncano APIs; and
          Specifications describing the operational and functional capabilities, use limitations, technical and engineering requirements, and testing and performance criteria relevant to the proper use of a Service and its related APIs.
          (b) Syncano may make available under another license agreement, such as an open source agreement, additional content or software. Any such content or software will be clearly marked with such a license indicating the usage rights available for that content or software. For such content or software released pursuant to an open license, Syncano encourages You to modify, alter, tamper with, repair and/or create derivative works consistent with such license. Such content or software may include:
          Developer tools, such as software development kits or sample code, for use in connection with the APIs; and
          Articles and documentation for use in connection with the use and implementation of the APIs (collectively, "Documentation").
          (c) Except as may be expressly authorized under this Agreement:
          You may not, and may not attempt to, modify, alter, tamper with, repair, or otherwise create derivative works of any software included in the Syncano Properties.
          You may not, and may not attempt to, reverse engineer, disassemble, or decompile the Syncano Properties or the Services or apply any other process or procedure to derive the source code of any software included in the Syncano Properties.</p>
        <p>1.7 For purposes of this Agreement, Syncano hereby grants to You a limited, non-exclusive, non-transferable, non-sub-licensable, revocable license during the Term of this Agreement to display the trade names, trademarks, service marks, logos, domain names of Syncano (each, a “Syncano Mark”) for the purpose of promoting or advertising that You use the Services, solely in accordance with the terms and conditions of this Agreement. In return You hereby grant Syncano a limited, non-exclusive, non-transferable, non-sublicensable license during the Term of this Agreement to display Your trade names, trademarks, service marks, logos, domain names and the like for the purpose of promoting or advertising that You use the Services. In using Syncano Marks, You may not: (i) display a Syncano Mark in any manner that implies a relationship or affiliation with, sponsorship, or endorsement by Syncano; (ii) use Syncano’s Marks to disparage Syncano or its products or services; or (iii) display a Syncano Mark on a site that violates any law or regulation. Notwithstanding the above, Syncano may determine in its sole discretion whether its marks may be used in connection with Your Application. Furthermore, we may modify any Syncano Marks provided to You at any time, and upon notice, You will use only the modified Syncano Marks and not the old Syncano Marks. Other than as specified in this Agreement, You may not use any Syncano Mark unless You obtain our prior written consent. All uses of the Syncano Trademarks and goodwill associated therewith shall inure to the benefit of Syncano.</p>
        <p>1.8 The rights granted by us in this Agreement with respect to the Syncano Properties, the Syncano Marks and the Services are nonexclusive, and we reserve the right to: (i) act as a developer of products or services related to any of the products that You may develop in connection with the Syncano Properties or via Your use of the Services; and (ii) appoint third parties as developers or systems integrators who may offer products or services which compete with Your Application.</p>
        <p>1.9 Subject to our commercially reasonable efforts and so long as Your account remains in good standing, data generated by Your use of the Service will remain available via our API for at least six months from the date such data was generated. Notwithstanding the above and without limitation to Section 7, we shall have no liability whatsoever for any damage, liabilities, losses (including any loss of data or profits) or any other consequences that You may incur with respect to loss of data associated with Your account and data therein.</p>
  
        <h3>2. Term, Termination and Suspension</h3>
        <p>2.1 The term (“Term”) of this Agreement will commence once You accept this Agreement as provided above. The Agreement will remain in effect until terminated by You or Syncano in accordance with this Section 2.
        </p>
        <p>2.2 You may terminate this Agreement for any reason or no reason at all, at Your convenience, by closing Your account for any Service for which we provide an account closing mechanism.
        </p>
        <p>2.3 Notwithstanding anything to the contrary in Section 1.9 or elsewhere, we may suspend Your right and license to use any or all Services or terminate this Agreement in its entirety (and, accordingly, cease providing all Services to You), for any reason or for no reason, at our discretion at any time by providing You thirty (30) days’ advance notice in accordance with the notice provisions set forth in Section 10 below. If Syncano determines that providing advance notice would negatively impact Syncano’s ability to provide Services, Syncano may suspend Your right and license to use any or all Services or terminate this Agreement in its entirety (and, accordingly, cease providing all Services to You), with no notice.
        </p>
        <p>2.4 We may suspend Your right and license to use the Service or terminate this Agreement in its entirety (and, accordingly, Your right to use the Service), for cause effective as set forth below:
          2.4.1 Immediately upon our notice to You in accordance with the notice provisions set forth in Section 10 below if (i) You violate any provision of the Acceptable Use Policy or we have reason to believe that You have violated the Acceptable Use Policy, (ii) there is an unusual spike or increase in Your use of the Services for which there is reason to believe such traffic or use is fraudulent or negatively impacting the operating capability of the Service; (iii) we determine, in our sole discretion, that our provision of any of the Services to You is prohibited by applicable law, or has become impractical or unfeasible for any legal or regulatory reason; or (iv) subject to applicable law, upon Your liquidation, commencement of dissolution proceedings, disposal of Your assets, failure to continue Your business, assignment for the benefit of creditors, or if You become the subject of a voluntary or involuntary bankruptcy or similar proceeding, or otherwise admit Your inability to comply with obligations or pay debts.
          2.4.2 Immediately and without notice if You are in default of any payment obligation with respect to any of the Services or if any payment mechanism You have provided to us is invalid or charges are refused for such payment mechanism.
          2.4.3 Five (5) days following our provision of notice to You in accordance with the notice provisions set forth in Section 10 below if You breach any other provision of this Agreement and fail, as determined by us, in our sole discretion, to cure such breach within such 5-day period.
        </p>
        <p>2.5 Effect of Suspension or Termination.
          2.5.1 Upon our suspension of Your use of any Services, in whole or in part, for any reason: (i) fees will continue to accrue for any Services that are still in use by You, notwithstanding the suspension; (ii) You remain liable for all fees, charges and any other obligations You have incurred through the date of suspension with respect to the Services; and (iii) all of Your rights with respect to the Services shall be terminated during the period of the suspension.
          2.5.2 Upon termination of this Agreement for any reason: (i) You remain liable for all fees, charges and any other obligations You have incurred through the date of termination with respect to the Services; and (ii) all of Your rights under this Agreement shall immediately terminate.
        </p>
        <p>2.6 In the event this Agreement expires or is cancelled or terminated for any reason, Sections 6, 7, 8, 9, 10 and 11 and any applicable definitions will survive any such expiration, cancellation or termination.
        </p>
        <p>2.7 Following the suspension or termination of Your right to use the Services by us or by You for any reason other than a termination for cause, You shall be entitled to take advantage of any post-termination assistance we may generally elect to make available with respect to the Services such as data retrieval arrangements. We may also endeavor to provide You with unique post-suspension or post-termination assistance, but we shall be under no obligation to do so. Your right to take advantage of any such assistance, whether generally made available with respect to the Services or made available uniquely to You, shall be conditioned upon Your acceptance of and compliance with any fees and terms we specify for such assistance.</p>
  
        <h3>3. Downtime and Service Suspensions; Security</h3>
        <p>3.1 In addition to our rights to terminate or suspend Services to You as described in Section 2 above, You acknowledge that: (i) Your access to and use of the Services may be suspended for the duration of any unanticipated or unscheduled downtime or unavailability of any portion or all of the Services for any reason, including as a result of power outages, system failures or other interruptions; and (ii) we shall also be entitled, without any liability to You, to suspend access to any portion or all of the Services at any time, on a Service-wide basis: (a) for scheduled downtime to permit us to conduct maintenance or make modifications to any Service; (b) in the event of a denial of service attack or other attack on the Service or other event that we determine, in our sole discretion, may create a risk to the applicable Service, to You or to any of our other customers if the Service were not suspended; or (c) in the event that we determine that any Service is prohibited by applicable law or we otherwise determine that it is necessary or prudent to do so for legal or regulatory reasons (collectively, “Service Suspensions”). Without limitation to Section 7, we shall have no liability whatsoever for any damage, liabilities, losses (including any loss of data or profits) or any other consequences that You may incur as a result of any Service Suspension. To the extent we are able, we will endeavor to provide You notice of any Service Suspension in accordance with the notice provisions set forth in Section 10 below and to post updates regarding resumption of Services following any such suspension, but shall have no liability for the manner in which we may do so or if we fail to do so.
        </p>
        <p>3.2 We strive to keep information You provide to us secure, but cannot guarantee that we will be successful at doing so. Accordingly, without limitation to Section 7 below, You acknowledge that You bear sole responsibility for adequate security, protection and backup of Your content. We strongly encourage You, where available and appropriate, to use encryption technology to protect Your content from unauthorized access and to routinely archive Your content. We will have no liability to You for any unauthorized access or use, corruption, deletion, destruction or loss of any of Your content.</p>
  
        <h3>4. Promotional Credits</h3>
        <p>4.1 We may award bonus codes, credits, points or any of our other virtual currencies (each individually or collectively referred to as “Promotional Credits”) in connection with promotions or other giveaways. Acquisition of Promotional Credits provides only a limited, non-transferable, non-sublicensable, revocable license to use such Promotional Credits to access Services that we expressly make available for use with the Promotional Credits. Promotional Credits have no monetary value and do not constitute currency or property of any type. Promotional Credits may not be sold or transferred, and cannot be exchanged for cash or for any other goods or services, except for Services. We may cancel any Promotional Credits transferred, assigned or sold in violation of this Agreement.
        </p>
        <p>4.2 Promotional Credits are limited to the user account it has been registered to and one user account can only have Promotional Credit code registered, and the one with the highest amount will be effective while any other registered Promotional Credits will be void. For the avoidance of doubt, even if there each user account can have more than one instance, any Promotional Credits granted by Syncano is limited to the user account and not per instance.
        </p>
        <p>4.3 The term of Your Promotional Credits license starts when You acquire such Promotional Credits and, subject to this Agreement, expires upon the earlier of (a) twelve months from the date of award (as the context requires and applicable to each individual award); or (b) the date set when the Promotional Credits were acquired. If You do not use Your account for six months, or if You delete Your account, any remaining Promotional Credits may be redeemed, cancelled or expired by us. Once Promotional Credits are redeemed for Services, such Services are not returnable, exchangeable or refundable for Promotional Credits or any other virtual currency, or for cash or goods or services.
        </p>
        <p>4.4 Promotional Credits may only be held by legal residents of countries where access to and use of the Services and Promotional Credits are permitted. Promotional Credits may only be awarded by us or through means we provide on the Website or otherwise expressly authorize. We can cancel or suspend Your access to Promotional Credits in our sole discretion and without prior notice, if (a) You fail to comply with this Agreement; or (b) if we otherwise suspect fraud or misuse of Promotional Credits. We have no obligation or responsibility to, and will not reimburse You for, any Promotional Credits lost due to such cancellation or suspension.
        </p>
        <p>4.5 We have the absolute right to offer, manage, regulate, modify and/or eliminate Promotional Credits or any portion thereof, at any time, without any liability to You.</p>
        <h3>5. Fees</h3>
        <p>5.1 You agree to pay all applicable fees as set forth in the Syncano Web Page from time to time. We may increase or add new fees for any existing Service or Service feature by giving You 30 days’ advance notice. All amounts payable hereunder exclude all applicable sales, use and other taxes.  Client will be responsible for payment of all such applicable taxes (other than taxes based on Syncano's net income), and any related penalties and interest arising from the payment of taxes hereunder.
        </p>
        <p>5.2 In its sole discretion, Syncano shall determine whether and which level of discount you are eligible for from time to time.
        </p>
        <p>5.3 We may specify the manner in which You will pay any fees, and any such payment shall be subject to our general accounts receivable policies from time to time in effect. All amounts payable by You under this Agreement will be made without setoff or counterclaim and without deduction or withholding. If any deduction or withholding is required by applicable law, You shall notify us and shall pay such additional amounts to us as necessary to ensure that the net amount that we receive, after such deduction and withholding, equals the amount we would have received if no such deduction or withholding had been required. Additionally, You shall provide us with documentation that the withholding and deducted amounts have been paid to the relevant taxing authority.
        </p>
        <p>5.4 Should You have any claim and/or disputes as to fees associated with Your account, please contact us at hello@syncano.com within 90 days of the date of the activity that generated such dispute, and we will attempt to resolve the matter. Any and all refunds issued to resolve such a dispute shall be issued as credits to Your account, but in no event shall there be any cash refunds. Claims and/ or disputes older than 90 days shall not be entitled to any refunds or credits.</p>
  
        <h3>6. Intellectual Property</h3>
        <p>6.1 Other than the limited use and access rights and licenses expressly set forth in this Agreement, we reserve all right, title and interest (including all intellectual property and proprietary rights) in and to: (i) the Services; (ii) the Syncano Properties; (iii) the Syncano Marks; and (iv) any other technology and software that we provide or use to provide the Services and the Syncano Properties. You do not, by virtue of this Agreement or otherwise, acquire any ownership interest or rights in the Services, the Syncano Properties, the Syncano Marks, or such other technology and software, except for the limited use and access rights described in this Agreement.
        </p>
        <p>6.2 Syncano may, at its discretion, offer certain Software Development Kits, tools, application samples, or documentation under an open source license. Any such products will be marked with copyright details, and those copyrights will apply to those and only those documents. Syncano reserves all rights to any documents, tools, services, technologies and the like not designated with an open license.
        </p>
        <p>6.3 Other than the rights and interests expressly set forth in this Agreement and excluding any and all works derived from Syncano Properties, You reserve all right, title and interest (including all intellectual property and proprietary rights) in and to: (i) content and data You may send to us or use as part of Your use of any Services (“Your Content”); and (ii) Your Applications.
        </p>
        <p>6.4 In the event You elect, in connection with any of the Services, to communicate to us suggestions for improvements to the Services, the Syncano Properties or the Syncano Marks (collectively, “Feedback”), we shall own all right, title, and interest in and to the same, even if You have designated the Feedback as confidential, and we shall be entitled to use the Feedback without restriction. Furthermore, any other content or information You post or provide to Syncano via comments, forums, emails and the like (collectively, “Communications”) shall be considered the property of Syncano. You hereby irrevocably assign all right, title and interest in and to the Feedback and Communications to us and agree to provide us such assistance as we may reasonably require documenting, perfecting, and maintaining our rights to the Feedback and Communications.
        </p>
        <p>6.5 During and after the Term of the Agreement, with respect to any of the Services that You elect to use, You will not assert, nor will You authorize, assist, or encourage any third party to assert, against us or any of our customers, end users, vendors, business partners (including third party sellers on websites operated by or on behalf of us), sub-licensees or transferees, any patent infringement or other intellectual property infringement claim with respect to such Services.
        </p>
        <p>6.6 Syncano respects the intellectual property of others, and we ask our users to do the same. If You believe that Your work has been copied in a way that constitutes copyright infringement, or that Your intellectual property rights have been otherwise violated, You should notify Syncano of Your infringement claim in accordance with the procedure set forth below.
        </p>
        <p>6.7 You acknowledge and agree that, pursuant to the Digital Millennium Copyright Act (“DMCA”), Syncano may respond in accordance with the requirements of the DMCA to “take-down” notices from third parties which allege that the inclusion in the System of information that you provide violates their copyrights. In so doing, Syncano may elect to remove (or require you to remove) such allegedly infringing information from the System unless you object to the allegation of infringement, in which case Syncano in its sole discretion may elect to maintain or restore the allegedly infringing information to the System pending the outcome of litigation which you may institute against the alleged copyright owner pursuant to the DMCA.  You will cooperate fully with Syncano to assure compliance with the DMCA upon receipt by Syncano of any “take-down” notice issued by any third party, and in so doing, to promptly inform Syncano whether you object to any such “take-down” notice and, if so, whether you will institute litigation to challenge the allegations of copyright infringement.
          a.	Notice and Procedure for Making Claims of Copyright Infringement
          Syncano respects the intellectual property of others. If you believe that your work has been copied in a way that constitutes copyright infringement, please provide Syncano’s copyright agent the written information specified below:
          •	An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;
          •	A description of the copyrighted work or works that you claim have been infringed upon;
          •	A description of where the material that you claim is infringing is located on the Site;
          •	Your address, telephone number, and e-mail address;
          •	A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and
          •	A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. Syncano’s Copyright Agent for notice of claims of copyright infringement on the Syncano Site can be reached as follows:
  
          Syncano
          120 East 23rd Street
          New York, NY 10010
          ATTN: DMCA Copyright Agent
  
          Email notifications may be sent to sara.cowie@syncano.com
  
          Please note that this procedure is exclusively for notifying Syncano and its subsidiaries that your copyrighted material has been infringed.</p>
  
        <h3>7. Representations and Warranties; Disclaimers; Limitations of Liability</h3>
        <p>7.1 You represent and warrant that You will not use the Website (including our forums and comments sections), Services, Syncano Properties, Syncano Marks, Your Application or Your Content in a manner that violates the Acceptable Use Policy. To this effect, we ask that You take reasonable precautions to promote best practices. Although Syncano does not assume the duty or obligation to monitor any materials created, posted or uploaded by You or any third parties, Syncano reserves the right, in its sole and absolute discretion, to monitor any and all materials posted or uploaded by You or any third parties at any time without prior notice to ensure that they conform to any usage guidelines or policies (including our Acceptable Use Policy) relating to our Website or Services.
        </p>
        <p>7.2 You represent and warrant: (i) that You are solely responsible for the development, operation, and maintenance of Your Application and for Your Content, including without limitation, the accuracy, appropriateness and completeness of Your Content and all product-related materials and descriptions; (ii) that You have the necessary rights and licenses, consents, permissions, waivers and releases to use and display Your Application and Your Content; (iii) that neither Your Application nor Your Content (a) violates, misappropriates or infringes any rights of us or any third party, (b) constitutes defamation, invasion of privacy or publicity, or otherwise violates any rights of any third party, or (c) is designed for use in any illegal activity or promotes illegal activities, including, without limitation, in a manner that might be libelous or defamatory or otherwise malicious, illegal or harmful to any person or entity, or discriminatory based on race, sex, religion, nationality, disability, sexual orientation, or age; (iv) that neither Your Application nor Your Content contains any harmful components; and (v) to the extent to which You use any of the Syncano Marks, that You will conduct Your business in a professional manner and in a way that reflects favorably on the goodwill and reputation of Syncano. You also represent and warrant that You are responsible for any charges incurred by virtue of Your use of the Application, no matter whether the Application acted in error.
        </p>
        <p>7.3 You represent and warrant that You have read and understood the Acceptable Use Policy, Privacy Policy and General Terms and Conditions, and You agree to abide by their terms, where applicable, including as incorporated by reference herein. You further agree to abide by all applicable local, state, national, foreign and international laws and regulations and that You will be solely responsible for all acts or omissions that occur under Your account or password, including the content of Your transmissions through the Service. By way of example, and not as a limitation, You agree not to violate any provisions of the Acceptable Use Policy.
  
          RESTRICTIONS ON USE:
          YOU ACKNOWLEDGE THAT YOU ARE RESPONSIBLE FOR COMPLIANCE WITH ALL RULES, LAWS AND REGULATIONS, INCLUDING BUT NOT LIMITED TO THE PRIVACY AND SECURITY RULES OF THE HEALTH INFORMATION AND PORTABILITY ACT OF 1996 (“HIPAA”) AS APPLICABLE, OTHER UNITED STATES FEDERAL LAWS AND REGULATIONS, UNITED STATES STATE LAWS AND REGULATIONS AND DATA PROTECTION AND PRIVACY LAWS OF EUROPEAN UNION MEMBER STATES AND LAWS AND REGULATIONS OF COUNTRIES BEYOND THE UNITED STATES AND THE EUROPEAN UNION AND WILL BEAR ANY AND ALL LIABILITY RESULTING FROM YOUR VIOLATION OF ANY SUCH RELEVANT RULE, LAW OR REGULATION, INCLUDING RELEVANT PRIVACY AND DATA PROTECTION LAWS, UNDER THE INDEMNIFICATION PROVISIONS OF THIS AGREEMENT, UPLOADED OR OTHERWISE SENT TO THE SERVICE OR ANY OF ITS THIRD-PARTY BUSINESS PARTNERS .
          7.3.1 Syncano has certified as a member of the EU and Swiss Harbor Frameworks operated by the U.S. Department of Commerce and enforced by the Federal Trade Commission and adheres to the U.S.-EU and U.S-Swiss Safe Harbor Framework principles with respect to the transfer, processing and security of any Personal Data transferred from the European Economic Area or Switzerland to the United States.
          To the extent Syncano Processes any Personal Data on Your behalf in connection with use of the Services by You, Your Agents and/or End-Users, Syncano and You hereby agree that You shall be deemed to be the data controller and Syncano shall be deemed to be the data processor as those terms are understood under Directive 95/46/EC on the Protection of Individuals With Regard to the Processing of Personal Data and on the Free Movement of Such Data (and any applicable national legislation implementing the Directive).  By utilizing the Services, You consent, on behalf of You and Your Agents and End-Users (and represent that You have the authority to consent on behalf of Your Agents and End-Users) to the Processing of Your Data, including, without limitation, any Personal Data, within the Syncano Group and to other authorized service providers pursuant to these Terms and Our Privacy Policy within the European Economic Area, the United States and in other countries and territories.
          Your Data is currently hosted by Syncano or its authorized service partners in data centers located in the United States or the European Economic Area.  If Your principal location is within the European Economic Area or the United States, We will use commercially reasonable efforts to notify You at least thirty (30) days before Our election to host Personal Data provided to Syncano in connection with use of the Service in data centers located outside the European Economic Area or the United States.  If You are entitled to this notice and do not wish to have Your Personal Data hosted in data centers located in such other country or territory, You may terminate Your Account with immediate effect upon written notice to Syncano within thirty (30) days or Your receipt of such notice.  For avoidance of doubt, the foregoing shall not, in any event, be deemed to limit any other manner of Processing of such Personal Data within Syncano or to authorize service providers whether in the European Economic Area, the United States or elsewhere.
        </p>
        <p>7.4 You represent and warrant that without Syncano’s express written consent You will not use, and will not authorize any third party to use, any Public Software (as defined below) in connection with the Services in any manner that requires, pursuant to the license applicable to such Public Software, that any Syncano Properties or Services be (a) disclosed or distributed in source code form, (b) made available free of charge to recipients, or (c) modifiable without restriction by recipients. With respect to any Feedback or Communications, You represent and warrant that such Feedback and Communications, in whole or in part, contributed by or through You, (i) is legally distributable by You, either because You own the copyright or because You have fully complied with any copyright terms associated with the software or content, (ii) contains no third party software or any software that may be considered Public Software and (iii) does not violate, misappropriate or infringe any intellectual property rights of any third party. “Public Software” means any software, documentation or other material that contains, or is derived (in whole or in part) from, any software, documentation or other material that is distributed as free software, open source software (e.g., Linux) or similar licensing or distribution models, including, but not limited to software, documentation or other material licensed or distributed under any of the following licenses or distribution models, or licenses or distribution models similar to any of the following: (i) GNU’s General Public License (GPL), Lesser/Library GPL (LGPL), or Free Documentation License, (ii) The Artistic License (e.g., PERL), (iii) the Mozilla Public License, (iv) the Netscape Public License, (v) the Sun Community Source License (SCSL), (vi) the Sun Industry Standards License (SISL), (vii) the BSD License and (viii) the Apache License.
        </p>
        <p>7.5 You represent and warrant that: (i) the information You provide in connection with Your registration for the Services is accurate and complete; (ii) You are duly authorized to do business in the jurisdiction where You operate; and (iii) You are an authorized representative of Your entity duly authorized to access the Services and to legally bind You to this Agreement and all transactions conducted under Your account.
        </p>
        <p>7.6 SYNCANO PROPERTIES, THE SYNCANO MARKS, THE SERVICES AND ALL TECHNOLOGY, SOFTWARE, FUNCTIONS, CONTENT, IMAGES, MATERIALS AND OTHER DATA OR INFORMATION PROVIDED BY US OR OUR LICENSORS IN CONNECTION THEREWITH (COLLECTIVELY THE “SERVICE OFFERINGS”) ARE PROVIDED “AS IS.” WE AND OUR LICENSORS MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE WITH RESPECT TO THE SYNCANO PROPERTIES, THE SYNCANO MARKS, THE SERVICES OR THE PROMOTIONAL CREDITS. EXCEPT TO THE EXTENT PROHIBITED BY APPLICABLE LAW, WE AND OUR LICENSORS DISCLAIM ALL WARRANTIES, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, TITLE, QUIET ENJOYMENT, AND ANY WARRANTIES ARISING OUT OF ANY COURSE OF DEALING OR USAGE OF TRADE. WE AND OUR LICENSORS DO NOT WARRANT THAT THE SERVICES OR WEBSITE WILL FUNCTION AS DESCRIBED, WILL BE UNINTERRUPTED OR ERROR FREE, OR FREE OF HARMFUL COMPONENTS, OR THAT THE DATA YOU STORE WITHIN THE SERVICES WILL BE SECURE OR NOT OTHERWISE LOST OR DAMAGED. WE AND OUR LICENSORS SHALL NOT BE RESPONSIBLE FOR ANY SERVICE OR WEBSITE INTERRUPTIONS, INCLUDING, WITHOUT LIMITATION, POWER OUTAGES, SYSTEM FAILURES OR OTHER INTERRUPTIONS. NO ADVICE OR INFORMATION OBTAINED BY YOU FROM US OR FROM ANY THIRD PARTY OR THROUGH THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS AGREEMENT.
        </p>
        <p>7.7 In addition to the foregoing, we specifically disclaim all liability, and You shall be solely responsible for the development, operation, and maintenance of Your Application and for all materials that appear on or within Your Application and Your Content and You agree that You shall, without limitation, be solely responsible for:
          7.7.1 the technical operation of Your Application and all related equipment;
          7.7.2 the accuracy and appropriateness of any materials posted on or within Your Application or Your Content (including, among other things, any product-related materials);
          7.7.3 ensuring that any materials posted on Your site or within Your Application do not violate our Acceptable Use Policy, are not illegal and do not promote illegal activities, including without limitation any activities that might be libelous or defamatory or otherwise malicious, illegal or harmful to any person or entity, or discriminatory based on race, sex, religion, nationality, disability, sexual orientation, or age;
          7.7.4 ensuring that Your Application accurately and adequately discloses, either through a privacy policy or otherwise, how You collect, use, store, and disclose data collected from visitors, including, where applicable, that third parties (including advertisers) may serve content and/or advertisements and collect information directly from visitors and may place or recognize cookies on visitors’ browsers; and
          7.7.5 any of Your users’ or customers’ claims relating to Your Application or Your Content or any Services utilized in connection with Your Application.
        </p>
        <p>7.8 NEITHER WE NOR ANY OF OUR LICENSORS SHALL BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER LOSSES (EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES) IN CONNECTION WITH THIS AGREEMENT, INCLUDING, WITHOUT LIMITATION, ANY SUCH DAMAGES RESULTING FROM: (i) THE USE OR THE INABILITY TO USE Syncano PROPERTIES, THE Syncano MARKS, THE SERVICES OR PROMOTIONAL CREDITS; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES; OR (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR CONTENT. IN ANY CASE, OUR AGGREGATE LIABILITY UNDER THIS AGREEMENT SHALL BE LIMITED TO THE AMOUNT ACTUALLY PAID BY YOU TO US HEREUNDER FOR THE SERVICES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OR ALL OF THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.
        </p>
        <p>7.9 YOU ACKNOWLEDGE THAT ACCESS TO THE SERVICES WILL BE PROVIDED OVER VARIOUS FACILITIES AND COMMUNICATIONS LINES, AND INFORMATION WILL BE TRANSMITTED OVER LOCAL EXCHANGE AND INTERNET BACKBONE CARRIER LINES AND THROUGH ROUTERS, SWITCHES, AND OTHER DEVICES (COLLECTIVELY, "CARRIER LINES") OWNED, MAINTAINED, AND SERVICED BY THIRD-PARTY CARRIERS, UTILITIES, AND INTERNET SERVICE PROVIDERS, ALL OF WHICH ARE BEYOND OUR CONTROL.  SYNCANO ASSUMES NO LIABILITY FOR OR RELATING TO THE INTEGRITY, PRIVACY, SECURITY, CONFIDENTIALITY, OR USE OF ANY INFORMATION WHILE IT IS TRANSMITTED ON THE CARRIER LINES, OR ANY DELAY, FAILURE, INTERRUPTION, INTERCEPTION, LOSS, TRANSMISSION, OR CORRUPTION OF ANY DATA OR OTHER INFORMATION ATTRIBUTABLE TO TRANSMISSION ON THE CARRIER LINES.  USE OF THE CARRIER LINES IS SOLELY AT YOUR RISK AND IS SUBJECT TO ALL APPLICABLE LOCAL, STATE, NATIONAL, AND INTERNATIONAL LAWS. YOU AGREE THAT SYNCANO TAKES NO RESPONSIBILITY FOR AND DISCLAIMS ANY AND ALL LIABILITY ARISING FROM ANY LOSS OF OR INACCURACIES OR DEFECTS IN THE INFORMATION, SOFTWARE, COMMUNICATION LINES, INTERNET OR YOUR INTERNET SERVICE PROVIDER (“ISP”), COMPUTER HARDWARE OR SOFTWARE, OR ANY OTHER SERVICE OR DEVICE THAT YOU USE TO ACCESS THE SERVICES. ADDITIONALLY, YOU ARE RESPONSIBLE FOR STORING, COPYING OR PRINTING COPIES OF YOUR INFORMATION IF YOU WANT TO HAVE THE INFORMATION AVAILABLE IN THE EVENT THAT THE SERVICES IS UNAVAILABLE.
        </p>
        <p>7.10 Certain content, products, and services available via the Syncano Website (or links contained therein) may include materials, software, plug-ins, applications and other resources from third parties and access to third party websites (collectively “Third Party Materials”). You acknowledge and agree that Syncano is not responsible for examining or evaluating the content or accuracy of any such Third Party Materials and that Syncano does not warrant or endorse and does not assume (and will not have) any liability or responsibility for any Third Party Materials or any damage or loss resulting therefrom. The availability of Third Party Materials is provided solely as a convenience to you. You agree that you must evaluate, and bear all risks associated with, the use of any Third Party Materials, including any reliance on the accuracy, completeness, or usefulness thereof. Please also remember that all use of the Syncano Website and service is subject to the Syncano Terms of Service.
          The Website may contain links or references to other independent third-party websites (the “Linked Sites”).  The Linked Sites are provided solely as a convenience to you and an information resource.  The Linked Sites are not hosted by or on Syncano’s servers or under Syncano’s control, maintained by Syncano or affiliated with any services provided by Syncano. Syncano is not responsible for the content, security, availability, accuracy or practices of the Linked Sites and expressly disclaims any responsibility for malware, worms, time bombs, bots, or any other harmful or deleterious programs or materials in said links or Linked Sites. You assume all risk and responsibility You or an agent, servant, employee or End User clicks on a link on the Website and You, on Your and their behalf, irrevocably waive any claim against Syncano for use of the Linked Sites.</p>
  
        <h3>8. Indemnification</h3>
        <p>8.1 You agree to indemnify, defend and hold us, our affiliates and licensors, each of our and their business partners (including third party sellers on websites operated by or on behalf of us) and each of our and their respective employees, officers, directors and representatives, harmless from and against any and all claims, losses, damages, liabilities, judgments, penalties, fines, costs and expenses (including reasonable attorneys fees), arising out of or in connection with any claim arising out of (i) Your use of the Services, Syncano Properties and/or Syncano Marks in a manner not authorized by this Agreement, and/or in violation of the applicable restrictions, the Acceptable Use Policy, and/or applicable law, (ii) Your Application, Your Content, or the combination of either with other applications, content or processes, including but not limited to any claim involving infringement or misappropriation of third-party rights and/or the use, development, design, manufacture, production, advertising, promotion and/or marketing of Your Application and/or Your Content, (iii) Your violation of any term or condition of this Agreement, the Acceptable Use Policy or any applicable additional policies, including without limitation, Your representations and warranties, or (iv) You or Your employees’ or personnel’s negligence or willful misconduct.
        </p>
        <p>8.2 We agree to promptly notify You of any claim subject to indemnification; provided that our failure to promptly notify You shall not affect Your obligations hereunder except to the extent that our failure to promptly notify You delays or prejudices Your ability to defend the claim. At our option, You will have the right to defend against any such claim with counsel of Your own choosing (subject to our written consent) and to settle such claim as You deem appropriate, provided that You shall not enter into any settlement without our prior written consent and provided that we may, at any time, elect to take over control of the defense and settlement of the claim.</p>
        <h3>9. Disputes</h3>
        <p>9.1 Notwithstanding anything to the contrary, we may seek injunctive or other relief in any state, federal, or national court of competent jurisdiction for any actual or alleged infringement of Syncano’s or any third party’s intellectual property rights and/or proprietary rights. You further acknowledge that our rights in the Syncano Services, Syncano Properties and the Syncano Marks are of a special, unique, extraordinary character, giving them peculiar value, the loss of which cannot be readily estimated and may not be adequately compensated for in monetary damages.
        </p>
        <p>9.2 By using the Services, You agree that the laws of the State of New York, without regard to principles of conflicts of laws, will govern this Agreement and any dispute of any sort that might arise between You and us.
        </p>
        <p>9.3 ARBITRATION. YOU AND SYNCANO BOTH AGREE TO RESOLVE DISPUTES ONLY BY ARBITRATION. THERE’S NO JUDGE OR JURY IN ARBITRATION, AND THE PROCEDURES MAY BE DIFFERENT, BUT AN ARBITRATOR CAN AWARD YOU THE SAME DAMAGES AND RELIEF, AND MUST HONOR THE SAME TERMS IN THIS AGREEMENT, AS A COURT WOULD. IF THE LAW ALLOWS FOR AN AWARD OF ATTORNEYS’ FEES, AN ARBITRATOR CAN AWARD THEM TOO. YOU AND SYNCANO ALSO BOTH AGREE THAT:
          9.3.1 THE FEDERAL ARBITRATION ACT APPLIES TO THIS AGREEMENT. ANY DISPUTE THAT IN ANY WAY RELATES TO OR ARISES OUT OF THIS AGREEMENT OR FROM ANY SERVICES YOU RECEIVE FROM US WILL BE RESOLVED BY ONE OR MORE NEUTRAL ARBITRATORS BEFORE THE AMERICAN ARBITRATION ASSOCIATION (“AAA”). YOU CAN ALSO BRING ANY ISSUES YOU MAY HAVE TO THE ATTENTION OF FEDERAL, STATE, OR LOCAL GOVERNMENT AGENCIES, AND IF THE LAW ALLOWS, THEY CAN SEEK RELIEF AGAINST US FOR YOU.
          9.3.2 UNLESS YOU AND SYNCANO AGREE OTHERWISE, THE ARBITRATION WILL TAKE PLACE IN NEW YORK, NEW YORK.
          9.3.3 THIS AGREEMENT DOESN’T ALLOW CLASS OR COLLECTIVE ARBITRATIONS. NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT, THE ARBITRATOR MAY AWARD MONEY OR INJUNCTIVE RELIEF ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF WARRANTED BY THAT PARTY’S INDIVIDUAL CLAIM. NO CLASS OR REPRESENTATIVE OR PRIVATE ATTORNEY GENERAL THEORIES OF LIABILITY OR PRAYERS FOR RELIEF MAY BE MAINTAINED IN ANY ARBITRATION HELD UNDER THIS AGREEMENT.
          9.3.4 IF EITHER YOU OR SYNCANO INTENDS TO SEEK ARBITRATION UNDER THIS AGREEMENT, THE PARTY SEEKING ARBITRATION MUST FIRST NOTIFY THE OTHER PARTY OF THE DISPUTE IN WRITING AT LEAST 30 DAYS IN ADVANCE OF INITIATING THE ARBITRATION. NOTICE TO SYNCANO SHOULD BE SENT AS REQUIRED BY THIS AGREEMENT. THE NOTICE MUST DESCRIBE THE NATURE OF THE CLAIM AND THE RELIEF BEING SOUGHT. IF YOU AND SYNCANO ARE UNABLE TO RESOLVE OUR DISPUTE WITHIN 30 DAYS, EITHER PARTY MAY THEN PROCEED TO FILE A CLAIM FOR ARBITRATION.
          9.3.5 AN ARBITRATION AWARD AND ANY JUDGMENT CONFIRMING IT APPLY ONLY TO THAT SPECIFIC CASE; IT CAN’T BE USED IN ANY OTHER CASE EXCEPT TO ENFORCE THE AWARD ITSELF.
          9.3.6 IF FOR SOME REASON THE PROHIBITION ON CLASS ARBITRATIONS SET FORTH IN SUBSECTION (3) CANNOT BE ENFORCED, THEN THE AGREEMENT TO ARBITRATE WILL NOT APPLY.
          9.3.7 IF FOR ANY REASON A CLAIM PROCEEDS IN COURT RATHER THAN THROUGH ARBITRATION, YOU AND SYNCANO AGREE THAT THERE WILL NOT BE A JURY TRIAL. YOU AND SYNCANO UNCONDITIONALLY WAIVE ANY RIGHT TO TRIAL BY JURY IN ANY ACTION, PROCEEDING OR COUNTERCLAIM ARISING OUT OF OR RELATING TO THIS AGREEMENT IN ANY WAY. IN THE EVENT OF LITIGATION, THIS PARAGRAPH MAY BE FILED TO SHOW A WRITTEN CONSENT TO A TRIAL BY THE COURT. YOU AND SYNCANO ALSO AGREE THAT ANY DISPUTE HEREUNDER SHALL BE ADJUDICATED IN ANY STATE OR FEDERAL COURT IN NEW YORK, AND YOU CONSENT TO EXCLUSIVE JURISDICTION AND VENUE IN SUCH COURTS.
  
        </p>
        <h3>10. Notices</h3>
        <p>10.1 Notices made by us under this Agreement for You or Your account specifically (e.g., notices of breach and/or suspension) will be provided to You via a notification message displayed on Your account page or via the email address provided to us in Your registration for the Services or in any updated email address You provide to us in accordance with standard account information update procedures we may provide from time to time. It is Your responsibility to keep Your email address current and You will be deemed to have received any email sent to any such email address, upon our sending of the email, whether or not You actually receive the email.
        </p>
        <p>10.2 For notices made by You to us under this Agreement and for questions regarding this Agreement or the Services, You may contact Syncano as follows: by contacting us at hello@syncano.com</p>
  
        <h3>11. Miscellaneous Provisions</h3>
        <p>11.1 Responsibility. If You authorize, assist, encourage or facilitate another person or entity to take any action related to the subject matter of this Agreement, You shall be deemed to have taken the action Yourself.
        </p>
        <p>11.2 Severability. If any portion of this Agreement is held by a court of competent jurisdiction to be invalid or unenforceable, the remaining portions of this Agreement will remain in full force and effect, and any invalid or unenforceable portions shall be construed in a manner that most closely reflects the effect and intent of the original language. If such construction is not possible, the provision will be severed from this Agreement, and the rest of the Agreement shall remain in full force and effect.
        </p>
        <p>11.3 Waivers. The failure by us to enforce any provision of this Agreement shall in no way be construed to be a present or future waiver of such provision nor in any way affect our right to enforce such provision thereafter. All waivers by us must be in writing to be effective.
        </p>
        <p>11.4 Successors and Assigns. This Agreement will be binding upon, and inure to the benefit of the parties and their respective successors and assigns.
        </p>
        <p>11.5 Entire Agreement. This Agreement incorporates by reference all policies and guidelines posted on the Syncano Website and as may be modified thereafter (including the Acceptable Use Policy, the General Terms and Conditions and the Privacy Policy) and constitutes the entire agreement between You and us regarding the subject matter hereof and supersedes any and all prior or contemporaneous representation, understanding, agreement, or communication between You and us, whether written or oral, regarding such subject matter.
        </p>
        <p>11.6 No Endorsement. You understand and acknowledge that we are not certifying nor endorsing, and have no obligation to certify or endorse, any of Your Applications or Your Content.
        </p>
        <p>11.7 International Sale of Goods; Export and Import Control Laws and Regulations. You and Syncano hereby agree to opt out from and expressly exclude any applicability of the Uniform Information Transactions Act (UCITA). Services, Content, and product derived or obtained from Syncano’s Services may be subject to the U.S. export laws and the export or import laws of other countries. You agree to comply strictly with all such laws and, in particular, shall: (a) obtain any export, reexport, or import authorizations required by U.S. or your local laws; (b) not use Services, Content, or direct product from Syncano’s Services to design, develop or produce missile, chemical/biological, or nuclear weaponry; and (c) not provide Services, Content, or direct product from Syncano’s Services to prohibited countries and entities identified in the U.S. export regulations
        </p>
        <p>11.8 No Agency. Nothing in this Agreement shall be construed as creating a partnership, contract of employment, agency, joint venture or franchise relationship between Syncano with You.
        </p>
        <p>11.9 No Third Party Beneficiary. You acknowledge and agree that, except as otherwise expressly provided in the Terms, there shall be no third party beneficiary to this agreement.</p>
  
        <h4>Last updated 1st July 2015</h4>
      </div>
    )
  }
});
